name: Build pipeline
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.1'

      - name: Run go vet
        run: go vet *.go

      - name: Run tests
        run: go test -race -vet=off

      - name: Build application
        run: go build -o bin/ttracker *.go