name: Build pipeline
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Run go vet
        run: go vet *.go
      - name: Run tests
        run: go test -race -v -vet=off ./tests
      - name: Build application
        run: go build -o bin/ttracker *.go