name: Overleaf Sync - Clone Thesis
on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.1' # The Go version to download (if necessary) and use.
          check-latest: true
          cache: true

      - name: Run go vet
        run: go vet *.go

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck *.go

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint *.go

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: make build